name: Tests

on:
  push:
    branches: [ main ]
    paths:
      - "src/**/*"
  pull_request:
    branches: [ main ]
    paths:
      - "src/**/*"

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm test
